export const productDataSet = [
  {
    id: 1,
    name: "Ciera",
    image:
      "https://robohash.org/temporibusvoluptatemsint.png?size=600x600&set=set1",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    brand: "Oldsmobile",
    category: "regional",
    price: 826.58,
    countInStock: 11,
    rating: 3.2,
    numReviews: 519,
  },
  {
    id: 2,
    name: "Impreza",
    image: "https://robohash.org/magninihilminus.png?size=600x600&set=set1",
    description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    brand: "Subaru",
    category: "core",
    price: 260.06,
    countInStock: 389,
    rating: 2.9,
    numReviews: 202,
  },
  {
    id: 3,
    name: "Grand Caravan",
    image: "https://robohash.org/quoveniamrerum.png?size=600x600&set=set1",
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    brand: "Dodge",
    category: "Stand-alone",
    price: 396.83,
    countInStock: 463,
    rating: 2.1,
    numReviews: 14,
  },
  {
    id: 4,
    name: "Quest",
    image: "https://robohash.org/etaliquamnesciunt.png?size=600x600&set=set1",
    description:
      "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    brand: "Nissan",
    category: "core",
    price: 777.91,
    countInStock: 79,
    rating: 1.3,
    numReviews: 501,
  },
  {
    id: 5,
    name: "RX-7",
    image:
      "https://robohash.org/consequunturadtenetur.png?size=600x600&set=set1",
    description:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    brand: "Mazda",
    category: "Organic",
    price: 132.79,
    countInStock: 391,
    rating: 1.1,
    numReviews: 342,
  },
  {
    id: 6,
    name: "Metro",
    image: "https://robohash.org/ullamvelitut.png?size=600x600&set=set1",
    description:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    brand: "Geo",
    category: "info-mediaries",
    price: 631.27,
    countInStock: 613,
    rating: 1.5,
    numReviews: 46,
  },
  {
    id: 7,
    name: "Express 2500",
    image: "https://robohash.org/autquodquisquam.png?size=600x600&set=set1",
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    brand: "Chevrolet",
    category: "encryption",
    price: 313.54,
    countInStock: 807,
    rating: 1.1,
    numReviews: 746,
  },
  {
    id: 8,
    name: "RSX",
    image:
      "https://robohash.org/perferendisquitenetur.png?size=600x600&set=set1",
    description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    brand: "Acura",
    category: "encryption",
    price: 406.95,
    countInStock: 189,
    rating: 1.3,
    numReviews: 137,
  },
  {
    id: 9,
    name: "M3",
    image: "https://robohash.org/sintvelvoluptates.png?size=600x600&set=set1",
    description:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    brand: "BMW",
    category: "contingency",
    price: 508.07,
    countInStock: 653,
    rating: 3.5,
    numReviews: 340,
  },
  {
    id: 10,
    name: "Tacoma",
    image:
      "https://robohash.org/mollitiaenimvoluptatem.png?size=600x600&set=set1",
    description:
      "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    brand: "Toyota",
    category: "protocol",
    price: 584.46,
    countInStock: 686,
    rating: 3.4,
    numReviews: 686,
  },
  {
    id: 11,
    name: "911",
    image:
      "https://robohash.org/mollitiaplaceatexpedita.png?size=600x600&set=set1",
    description:
      "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    brand: "Porsche",
    category: "Open-source",
    price: 374.48,
    countInStock: 696,
    rating: 1.2,
    numReviews: 234,
  },
  {
    id: 12,
    name: "Familia",
    image:
      "https://robohash.org/beataevoluptatibusvoluptas.png?size=600x600&set=set1",
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    brand: "Mazda",
    category: "process improvement",
    price: 508.33,
    countInStock: 348,
    rating: 1.3,
    numReviews: 37,
  },
  {
    id: 13,
    name: "Safari",
    image:
      "https://robohash.org/quiaccusamusvoluptas.png?size=600x600&set=set1",
    description:
      "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    brand: "Pontiac",
    category: "Triple-buffered",
    price: 210.52,
    countInStock: 982,
    rating: 3.1,
    numReviews: 84,
  },
  {
    id: 14,
    name: "Viper",
    image:
      "https://robohash.org/blanditiistotamcumque.png?size=600x600&set=set1",
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    brand: "Dodge",
    category: "frame",
    price: 749.7,
    countInStock: 401,
    rating: 2.4,
    numReviews: 633,
  },
  {
    id: 15,
    name: "Sentra",
    image:
      "https://robohash.org/cupiditatetemporibuset.png?size=600x600&set=set1",
    description:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    brand: "Nissan",
    category: "knowledge user",
    price: 232.07,
    countInStock: 93,
    rating: 1.5,
    numReviews: 207,
  },
  {
    id: 16,
    name: "SJ",
    image: "https://robohash.org/exsitreiciendis.png?size=600x600&set=set1",
    description:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    brand: "Suzuki",
    category: "Total",
    price: 436.91,
    countInStock: 74,
    rating: 3.6,
    numReviews: 65,
  },
  {
    id: 17,
    name: "Ram 1500 Club",
    image: "https://robohash.org/repudiandaeestaut.png?size=600x600&set=set1",
    description:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    brand: "Dodge",
    category: "instruction set",
    price: 474.23,
    countInStock: 81,
    rating: 2.0,
    numReviews: 3,
  },
  {
    id: 18,
    name: "Expedition",
    image: "https://robohash.org/quiaspernaturenim.png?size=600x600&set=set1",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    brand: "Ford",
    category: "Devolved",
    price: 931.63,
    countInStock: 474,
    rating: 3.0,
    numReviews: 905,
  },
  {
    id: 19,
    name: "H2",
    image: "https://robohash.org/uttemporequi.png?size=600x600&set=set1",
    description:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    brand: "Hummer",
    category: "discrete",
    price: 182.2,
    countInStock: 752,
    rating: 2.7,
    numReviews: 758,
  },
  {
    id: 20,
    name: "Vitara",
    image: "https://robohash.org/autoditimpedit.png?size=600x600&set=set1",
    description:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    brand: "Suzuki",
    category: "Pre-emptive",
    price: 833.23,
    countInStock: 530,
    rating: 2.9,
    numReviews: 522,
  },
  {
    id: 21,
    name: "9-5",
    image: "https://robohash.org/essepraesentiuma.png?size=600x600&set=set1",
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    brand: "Saab",
    category: "dedicated",
    price: 97.78,
    countInStock: 159,
    rating: 2.7,
    numReviews: 196,
  },
  {
    id: 22,
    name: "Intrigue",
    image:
      "https://robohash.org/consecteturplaceattempora.png?size=600x600&set=set1",
    description:
      "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    brand: "Oldsmobile",
    category: "Optional",
    price: 823.43,
    countInStock: 763,
    rating: 3.4,
    numReviews: 318,
  },
  {
    id: 23,
    name: "CL",
    image:
      "https://robohash.org/nemodoloremqueaccusamus.png?size=600x600&set=set1",
    description:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    brand: "Acura",
    category: "encoding",
    price: 549.48,
    countInStock: 270,
    rating: 3.2,
    numReviews: 28,
  },
  {
    id: 24,
    name: "Dakota Club",
    image: "https://robohash.org/eumoccaecatiaut.png?size=600x600&set=set1",
    description:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    brand: "Dodge",
    category: "focus group",
    price: 655.17,
    countInStock: 343,
    rating: 1.5,
    numReviews: 983,
  },
  {
    id: 25,
    name: "Spectra",
    image: "https://robohash.org/aliquamiurenulla.png?size=600x600&set=set1",
    description:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    brand: "Kia",
    category: "policy",
    price: 130.62,
    countInStock: 452,
    rating: 3.4,
    numReviews: 23,
  },
  {
    id: 26,
    name: "S80",
    image:
      "https://robohash.org/nonconsequaturpraesentium.png?size=600x600&set=set1",
    description:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    brand: "Volvo",
    category: "customer loyalty",
    price: 399.9,
    countInStock: 595,
    rating: 3.1,
    numReviews: 614,
  },
  {
    id: 27,
    name: "IS",
    image: "https://robohash.org/namoptiocorporis.png?size=600x600&set=set1",
    description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    brand: "Lexus",
    category: "process improvement",
    price: 822.82,
    countInStock: 596,
    rating: 1.5,
    numReviews: 113,
  },
  {
    id: 28,
    name: "Celica",
    image: "https://robohash.org/assumendacumlabore.png?size=600x600&set=set1",
    description:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    brand: "Toyota",
    category: "Function-based",
    price: 180.98,
    countInStock: 553,
    rating: 1.5,
    numReviews: 939,
  },
  {
    id: 29,
    name: "Virage",
    image: "https://robohash.org/numquamipsafugit.png?size=600x600&set=set1",
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    brand: "Aston Martin",
    category: "solution-oriented",
    price: 863.21,
    countInStock: 647,
    rating: 3.4,
    numReviews: 828,
  },
  {
    id: 30,
    name: "Outback",
    image: "https://robohash.org/quiquisvoluptate.png?size=600x600&set=set1",
    description:
      "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    brand: "Subaru",
    category: "directional",
    price: 904.54,
    countInStock: 401,
    rating: 2.1,
    numReviews: 958,
  },
  {
    id: 31,
    name: "B-Series Plus",
    image: "https://robohash.org/etnumquamsaepe.png?size=600x600&set=set1",
    description:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    brand: "Mazda",
    category: "Programmable",
    price: 952.9,
    countInStock: 901,
    rating: 1.6,
    numReviews: 417,
  },
  {
    id: 32,
    name: "A6",
    image: "https://robohash.org/sitillolabore.png?size=600x600&set=set1",
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    brand: "Audi",
    category: "6th generation",
    price: 958.9,
    countInStock: 659,
    rating: 2.3,
    numReviews: 884,
  },
  {
    id: 33,
    name: "Ram 1500",
    image: "https://robohash.org/nonnisiaut.png?size=600x600&set=set1",
    description:
      "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    brand: "Dodge",
    category: "Configurable",
    price: 188.18,
    countInStock: 135,
    rating: 3.0,
    numReviews: 115,
  },
  {
    id: 34,
    name: "V12 Vantage",
    image: "https://robohash.org/doloribusquiculpa.png?size=600x600&set=set1",
    description:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    brand: "Aston Martin",
    category: "fresh-thinking",
    price: 277.06,
    countInStock: 312,
    rating: 1.0,
    numReviews: 644,
  },
  {
    id: 35,
    name: "Rabbit",
    image:
      "https://robohash.org/deseruntdistinctioharum.png?size=600x600&set=set1",
    description:
      "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    brand: "Volkswagen",
    category: "Multi-layered",
    price: 606.89,
    countInStock: 26,
    rating: 3.1,
    numReviews: 938,
  },
  {
    id: 36,
    name: "Cooper",
    image:
      "https://robohash.org/atdistinctioexpedita.png?size=600x600&set=set1",
    description:
      "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    brand: "MINI",
    category: "Cross-platform",
    price: 775.52,
    countInStock: 656,
    rating: 2.7,
    numReviews: 836,
  },
  {
    id: 37,
    name: "DB9",
    image: "https://robohash.org/nisiadipisciet.png?size=600x600&set=set1",
    description:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    brand: "Aston Martin",
    category: "systematic",
    price: 345.22,
    countInStock: 992,
    rating: 3.4,
    numReviews: 546,
  },
  {
    id: 38,
    name: "RX Hybrid",
    image: "https://robohash.org/voluptatibusestnam.png?size=600x600&set=set1",
    description:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    brand: "Lexus",
    category: "circuit",
    price: 526.99,
    countInStock: 147,
    rating: 2.2,
    numReviews: 99,
  },
  {
    id: 39,
    name: "400SEL",
    image:
      "https://robohash.org/teneturvoluptatemiusto.png?size=600x600&set=set1",
    description:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    brand: "Mercedes-Benz",
    category: "concept",
    price: 765.96,
    countInStock: 425,
    rating: 2.0,
    numReviews: 615,
  },
  {
    id: 40,
    name: "Escort",
    image:
      "https://robohash.org/molestiaequoslaudantium.png?size=600x600&set=set1",
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    brand: "Ford",
    category: "Re-contextualized",
    price: 930.07,
    countInStock: 421,
    rating: 1.9,
    numReviews: 679,
  },
  {
    id: 41,
    name: "LS",
    image: "https://robohash.org/sedautaut.png?size=600x600&set=set1",
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    brand: "Lexus",
    category: "Focused",
    price: 238.5,
    countInStock: 405,
    rating: 3.7,
    numReviews: 450,
  },
  {
    id: 42,
    name: "Econoline E350",
    image:
      "https://robohash.org/temporibusabarchitecto.png?size=600x600&set=set1",
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    brand: "Ford",
    category: "bottom-line",
    price: 602.41,
    countInStock: 21,
    rating: 1.3,
    numReviews: 104,
  },
  {
    id: 43,
    name: "Ram 2500",
    image: "https://robohash.org/architectoquosneque.png?size=600x600&set=set1",
    description:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    brand: "Dodge",
    category: "Universal",
    price: 230.22,
    countInStock: 539,
    rating: 3.2,
    numReviews: 514,
  },
  {
    id: 44,
    name: "MX-6",
    image: "https://robohash.org/etdoloremexplicabo.png?size=600x600&set=set1",
    description:
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    brand: "Mazda",
    category: "Quality-focused",
    price: 454.89,
    countInStock: 816,
    rating: 1.4,
    numReviews: 907,
  },
  {
    id: 45,
    name: "Express 3500",
    image: "https://robohash.org/sitsedvoluptas.png?size=600x600&set=set1",
    description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    brand: "Chevrolet",
    category: "Grass-roots",
    price: 228.91,
    countInStock: 67,
    rating: 1.9,
    numReviews: 344,
  },
  {
    id: 46,
    name: "Expedition EL",
    image: "https://robohash.org/debitisullamearum.png?size=600x600&set=set1",
    description:
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    brand: "Ford",
    category: "Streamlined",
    price: 432.91,
    countInStock: 490,
    rating: 3.7,
    numReviews: 111,
  },
  {
    id: 47,
    name: "Silverado",
    image: "https://robohash.org/quinisiillo.png?size=600x600&set=set1",
    description: "Fusce consequat. Nulla nisl. Nunc nisl.",
    brand: "Chevrolet",
    category: "Digitized",
    price: 21.02,
    countInStock: 662,
    rating: 1.2,
    numReviews: 808,
  },
  {
    id: 48,
    name: "Golf",
    image: "https://robohash.org/nonessesit.png?size=600x600&set=set1",
    description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    brand: "Volkswagen",
    category: "access",
    price: 182.67,
    countInStock: 44,
    rating: 2.4,
    numReviews: 388,
  },
  {
    id: 49,
    name: "Grand Am",
    image: "https://robohash.org/velcorruptidolores.png?size=600x600&set=set1",
    description:
      "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    brand: "Pontiac",
    category: "Enhanced",
    price: 859.64,
    countInStock: 659,
    rating: 2.6,
    numReviews: 596,
  },
  {
    id: 50,
    name: "XK",
    image: "https://robohash.org/dolordoloribusanimi.png?size=600x600&set=set1",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    brand: "Jaguar",
    category: "responsive",
    price: 696.91,
    countInStock: 423,
    rating: 1.1,
    numReviews: 564,
  },
  {
    id: 51,
    name: "Diamante",
    image:
      "https://robohash.org/excepturioccaecatiporro.png?size=600x600&set=set1",
    description:
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    brand: "Mitsubishi",
    category: "4th generation",
    price: 291.1,
    countInStock: 807,
    rating: 3.3,
    numReviews: 506,
  },
  {
    id: 52,
    name: "Mustang",
    image:
      "https://robohash.org/expeditavoluptatemet.png?size=600x600&set=set1",
    description:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.",
    brand: "Ford",
    category: "foreground",
    price: 471.96,
    countInStock: 81,
    rating: 1.6,
    numReviews: 93,
  },
  {
    id: 53,
    name: "Oasis",
    image:
      "https://robohash.org/suscipitexplicabosint.png?size=600x600&set=set1",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    brand: "Isuzu",
    category: "superstructure",
    price: 208.5,
    countInStock: 443,
    rating: 2.0,
    numReviews: 346,
  },
  {
    id: 54,
    name: "Crown Victoria",
    image: "https://robohash.org/namexcepturieos.png?size=600x600&set=set1",
    description:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    brand: "Ford",
    category: "contingency",
    price: 265.68,
    countInStock: 561,
    rating: 1.8,
    numReviews: 218,
  },
  {
    id: 55,
    name: "Interceptor",
    image:
      "https://robohash.org/eligendinihillaborum.png?size=600x600&set=set1",
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    brand: "Jensen",
    category: "logistical",
    price: 395.27,
    countInStock: 870,
    rating: 2.8,
    numReviews: 329,
  },
  {
    id: 56,
    name: "LTD Crown Victoria",
    image:
      "https://robohash.org/quiapraesentiumvoluptate.png?size=600x600&set=set1",
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.",
    brand: "Ford",
    category: "global",
    price: 470.13,
    countInStock: 805,
    rating: 3.3,
    numReviews: 401,
  },
  {
    id: 57,
    name: "911",
    image: "https://robohash.org/blanditiisplaceatex.png?size=600x600&set=set1",
    description:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    brand: "Porsche",
    category: "collaboration",
    price: 366.53,
    countInStock: 927,
    rating: 3.7,
    numReviews: 155,
  },
  {
    id: 58,
    name: "Fleetwood",
    image:
      "https://robohash.org/nostrumquisconsequuntur.png?size=600x600&set=set1",
    description:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    brand: "Cadillac",
    category: "system-worthy",
    price: 594.62,
    countInStock: 360,
    rating: 2.1,
    numReviews: 388,
  },
  {
    id: 59,
    name: "300SD",
    image: "https://robohash.org/sitaccusantiumipsum.png?size=600x600&set=set1",
    description:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    brand: "Mercedes-Benz",
    category: "software",
    price: 839.63,
    countInStock: 446,
    rating: 3.2,
    numReviews: 926,
  },
  {
    id: 60,
    name: "Savana 2500",
    image: "https://robohash.org/nobisvelitmollitia.png?size=600x600&set=set1",
    description:
      "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    brand: "GMC",
    category: "leverage",
    price: 657.7,
    countInStock: 70,
    rating: 3.3,
    numReviews: 874,
  },
  {
    id: 61,
    name: "Alcyone SVX",
    image:
      "https://robohash.org/inventoreexpeditaprovident.png?size=600x600&set=set1",
    description:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    brand: "Subaru",
    category: "Realigned",
    price: 752.45,
    countInStock: 922,
    rating: 2.9,
    numReviews: 149,
  },
  {
    id: 62,
    name: "XT",
    image: "https://robohash.org/utaliascorrupti.png?size=600x600&set=set1",
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    brand: "Subaru",
    category: "actuating",
    price: 692.16,
    countInStock: 955,
    rating: 3.9,
    numReviews: 132,
  },
  {
    id: 63,
    name: "Bonneville",
    image: "https://robohash.org/quiareiciendisquos.png?size=600x600&set=set1",
    description:
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    brand: "Pontiac",
    category: "bandwidth-monitored",
    price: 240.94,
    countInStock: 824,
    rating: 3.7,
    numReviews: 592,
  },
  {
    id: 64,
    name: "riolet",
    image: "https://robohash.org/etblanditiisducimus.png?size=600x600&set=set1",
    description:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    brand: "Audi",
    category: "solution",
    price: 319.19,
    countInStock: 870,
    rating: 3.3,
    numReviews: 338,
  },
  {
    id: 65,
    name: "Esprit",
    image:
      "https://robohash.org/atquedelenitisapiente.png?size=600x600&set=set1",
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    brand: "Lotus",
    category: "Reduced",
    price: 203.61,
    countInStock: 159,
    rating: 2.3,
    numReviews: 678,
  },
  {
    id: 66,
    name: "4Runner",
    image: "https://robohash.org/nullatemporefugiat.png?size=600x600&set=set1",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    brand: "Toyota",
    category: "info-mediaries",
    price: 801.37,
    countInStock: 90,
    rating: 2.7,
    numReviews: 184,
  },
  {
    id: 67,
    name: "Protege5",
    image: "https://robohash.org/ametexid.png?size=600x600&set=set1",
    description:
      "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    brand: "Mazda",
    category: "optimal",
    price: 673.9,
    countInStock: 408,
    rating: 1.5,
    numReviews: 801,
  },
  {
    id: 68,
    name: "Durango",
    image: "https://robohash.org/utexplicabosuscipit.png?size=600x600&set=set1",
    description:
      "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    brand: "Dodge",
    category: "Team-oriented",
    price: 701.58,
    countInStock: 219,
    rating: 3.4,
    numReviews: 530,
  },
  {
    id: 69,
    name: "Quattroporte",
    image: "https://robohash.org/eosveroest.png?size=600x600&set=set1",
    description:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    brand: "Maserati",
    category: "solution",
    price: 987.43,
    countInStock: 221,
    rating: 3.9,
    numReviews: 821,
  },
  {
    id: 70,
    name: "RX",
    image: "https://robohash.org/utevenietiusto.png?size=600x600&set=set1",
    description:
      "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    brand: "Lexus",
    category: "Switchable",
    price: 782.97,
    countInStock: 621,
    rating: 3.7,
    numReviews: 589,
  },
  {
    id: 71,
    name: "Sephia",
    image:
      "https://robohash.org/voluptatemconsequatureligendi.png?size=600x600&set=set1",
    description:
      "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    brand: "Kia",
    category: "Pre-emptive",
    price: 47.82,
    countInStock: 469,
    rating: 3.8,
    numReviews: 428,
  },
  {
    id: 72,
    name: "RAV4",
    image: "https://robohash.org/sedessefugiat.png?size=600x600&set=set1",
    description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    brand: "Toyota",
    category: "Cloned",
    price: 615.06,
    countInStock: 577,
    rating: 1.3,
    numReviews: 715,
  },
  {
    id: 73,
    name: "Pilot",
    image:
      "https://robohash.org/eosassumendarepudiandae.png?size=600x600&set=set1",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    brand: "Honda",
    category: "Multi-lateral",
    price: 382.26,
    countInStock: 775,
    rating: 3.1,
    numReviews: 865,
  },
  {
    id: 74,
    name: "G-Class",
    image: "https://robohash.org/quisametquo.png?size=600x600&set=set1",
    description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    brand: "Mercedes-Benz",
    category: "Operative",
    price: 642.01,
    countInStock: 866,
    rating: 3.0,
    numReviews: 932,
  },
  {
    id: 75,
    name: "G37",
    image:
      "https://robohash.org/voluptasmolestiaesed.png?size=600x600&set=set1",
    description:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    brand: "Infiniti",
    category: "demand-driven",
    price: 443.51,
    countInStock: 231,
    rating: 1.4,
    numReviews: 399,
  },
  {
    id: 76,
    name: "Ranger",
    image:
      "https://robohash.org/adipiscivoluptateexcepturi.png?size=600x600&set=set1",
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    brand: "Ford",
    category: "Innovative",
    price: 560.82,
    countInStock: 597,
    rating: 3.5,
    numReviews: 78,
  },
  {
    id: 77,
    name: "G-Class",
    image: "https://robohash.org/maximeuteum.png?size=600x600&set=set1",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    brand: "Mercedes-Benz",
    category: "migration",
    price: 955.66,
    countInStock: 750,
    rating: 3.3,
    numReviews: 51,
  },
  {
    id: 78,
    name: "Legend",
    image: "https://robohash.org/estexcepturiet.png?size=600x600&set=set1",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    brand: "Acura",
    category: "installation",
    price: 905.56,
    countInStock: 808,
    rating: 1.2,
    numReviews: 442,
  },
  {
    id: 79,
    name: "Century",
    image: "https://robohash.org/ullamnonqui.png?size=600x600&set=set1",
    description:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    brand: "Buick",
    category: "leverage",
    price: 196.37,
    countInStock: 924,
    rating: 1.2,
    numReviews: 300,
  },
  {
    id: 80,
    name: "Rapide",
    image: "https://robohash.org/omnishicincidunt.png?size=600x600&set=set1",
    description:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    brand: "Aston Martin",
    category: "Public-key",
    price: 201.6,
    countInStock: 128,
    rating: 3.8,
    numReviews: 144,
  },
  {
    id: 81,
    name: "XK Series",
    image:
      "https://robohash.org/distinctionobisvoluptatem.png?size=600x600&set=set1",
    description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    brand: "Jaguar",
    category: "access",
    price: 823.22,
    countInStock: 387,
    rating: 3.2,
    numReviews: 720,
  },
  {
    id: 82,
    name: "Thunderbird",
    image: "https://robohash.org/animisuscipitrem.png?size=600x600&set=set1",
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    brand: "Ford",
    category: "analyzing",
    price: 472.27,
    countInStock: 559,
    rating: 3.4,
    numReviews: 166,
  },
  {
    id: 83,
    name: "LS",
    image: "https://robohash.org/inautincidunt.png?size=600x600&set=set1",
    description:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    brand: "Lexus",
    category: "infrastructure",
    price: 959.59,
    countInStock: 871,
    rating: 3.2,
    numReviews: 35,
  },
  {
    id: 84,
    name: "Camry",
    image:
      "https://robohash.org/remassumendavoluptatem.png?size=600x600&set=set1",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    brand: "Toyota",
    category: "upward-trending",
    price: 437.85,
    countInStock: 843,
    rating: 2.2,
    numReviews: 826,
  },
  {
    id: 85,
    name: "Yukon XL 2500",
    image:
      "https://robohash.org/saepealiquidcupiditate.png?size=600x600&set=set1",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    brand: "GMC",
    category: "hub",
    price: 301.07,
    countInStock: 91,
    rating: 1.9,
    numReviews: 232,
  },
  {
    id: 86,
    name: "57",
    image: "https://robohash.org/suntdoloresse.png?size=600x600&set=set1",
    description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    brand: "Maybach",
    category: "Automated",
    price: 515.51,
    countInStock: 203,
    rating: 1.2,
    numReviews: 457,
  },
  {
    id: 87,
    name: "Bonneville",
    image: "https://robohash.org/natusdelenitisit.png?size=600x600&set=set1",
    description:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    brand: "Pontiac",
    category: "artificial intelligence",
    price: 19.23,
    countInStock: 931,
    rating: 1.6,
    numReviews: 911,
  },
  {
    id: 88,
    name: "Paseo",
    image: "https://robohash.org/aliasadest.png?size=600x600&set=set1",
    description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    brand: "Toyota",
    category: "budgetary management",
    price: 254.33,
    countInStock: 14,
    rating: 1.8,
    numReviews: 630,
  },
  {
    id: 89,
    name: "GTI",
    image:
      "https://robohash.org/doloresapientedolorem.png?size=600x600&set=set1",
    description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    brand: "Volkswagen",
    category: "algorithm",
    price: 160.79,
    countInStock: 190,
    rating: 2.8,
    numReviews: 363,
  },
  {
    id: 90,
    name: "QX",
    image: "https://robohash.org/voluptasnatussit.png?size=600x600&set=set1",
    description:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    brand: "Infiniti",
    category: "Right-sized",
    price: 875.3,
    countInStock: 212,
    rating: 1.0,
    numReviews: 675,
  },
  {
    id: 91,
    name: "H3",
    image: "https://robohash.org/modietlibero.png?size=600x600&set=set1",
    description:
      "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    brand: "Hummer",
    category: "Decentralized",
    price: 964.89,
    countInStock: 722,
    rating: 3.6,
    numReviews: 211,
  },
  {
    id: 92,
    name: "Nitro",
    image: "https://robohash.org/acorruptiqui.png?size=600x600&set=set1",
    description:
      "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    brand: "Dodge",
    category: "circuit",
    price: 793.59,
    countInStock: 585,
    rating: 3.3,
    numReviews: 941,
  },
  {
    id: 93,
    name: "Armada",
    image: "https://robohash.org/isteillotemporibus.png?size=600x600&set=set1",
    description:
      "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    brand: "Nissan",
    category: "model",
    price: 97.97,
    countInStock: 11,
    rating: 1.8,
    numReviews: 641,
  },
  {
    id: 94,
    name: "Silhouette",
    image: "https://robohash.org/vitaeetvelit.png?size=600x600&set=set1",
    description: "Fusce consequat. Nulla nisl. Nunc nisl.",
    brand: "Oldsmobile",
    category: "implementation",
    price: 85.72,
    countInStock: 115,
    rating: 1.5,
    numReviews: 619,
  },
  {
    id: 95,
    name: "Impreza",
    image: "https://robohash.org/etconsequaturipsam.png?size=600x600&set=set1",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    brand: "Subaru",
    category: "matrix",
    price: 924.05,
    countInStock: 574,
    rating: 2.1,
    numReviews: 581,
  },
  {
    id: 96,
    name: "XC70",
    image: "https://robohash.org/quisetsit.png?size=600x600&set=set1",
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    brand: "Volvo",
    category: "hardware",
    price: 372.49,
    countInStock: 639,
    rating: 2.5,
    numReviews: 951,
  },
  {
    id: 97,
    name: "I",
    image: "https://robohash.org/isteteneturqui.png?size=600x600&set=set1",
    description:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    brand: "Infiniti",
    category: "superstructure",
    price: 913.71,
    countInStock: 194,
    rating: 2.3,
    numReviews: 684,
  },
  {
    id: 98,
    name: "4Runner",
    image: "https://robohash.org/repellatnatusrerum.png?size=600x600&set=set1",
    description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    brand: "Toyota",
    category: "local area network",
    price: 190.76,
    countInStock: 204,
    rating: 3.3,
    numReviews: 69,
  },
  {
    id: 99,
    name: "Ram 1500 Club",
    image: "https://robohash.org/adquiest.png?size=600x600&set=set1",
    description:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    brand: "Dodge",
    category: "secured line",
    price: 842.23,
    countInStock: 96,
    rating: 1.0,
    numReviews: 250,
  },
  {
    id: 100,
    name: "Defender",
    image:
      "https://robohash.org/blanditiisestcommodi.png?size=600x600&set=set1",
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    brand: "Land Rover",
    category: "array",
    price: 769.46,
    countInStock: 721,
    rating: 3.5,
    numReviews: 657,
  },
];
